(custom-set-faces
 '(info-xref ((((type x) (class color) (background light)) (:foreground "red3" :bold t :underline t)) 
	      (((type tty) (class color) (background dark)) (:foreground "brightred" :bold t))))
 '(gui-button-face ((t (:inverse-video t))) t)
 '(info-node ((((type x) (class color) (background light)) (:foreground "red3" :bold t)) 
	      (((type tty) (class color) (background dark)) (:foreground "brightred" :bold t))))
 '(dired-face-directory ((t (:foreground "blue" :bold t))))
 '(font-lock-string-face ((((type x) (class color) (background dark)) (:foreground "tan")) 
			  (((type x) (class color) (background light)) (:foreground "green4")) 
			  (((type x) (class grayscale) (background light)) (:foreground "DimGray" :italic t)) 
			  (((type x) (class grayscale) (background dark)) (:foreground "LightGray" :italic t)) 
			  (((type tty) (class color)) (:foreground "green")) (t (:bold t))))
 '(dired-face-permissions ((t (:foreground "black" :background "cyan"))))
 '(font-lock-reference-face ((((type tty) (class color)) (:foreground "brightyellow")) 
			     (((class color) (background dark)) (:foreground "cadetblue2")) 
			     (((class color) (background light)) (:foreground "red3")) 
			     (((class grayscale) (background light)) (:foreground "LightGray" :bold t :underline t)) 
			     (((class grayscale) (background dark)) (:foreground "Gray50" :bold t :underline t))))
 '(font-lock-doc-string-face ((((type tty) (class color)) (:foreground "brightgreen")) 
			      (((class color) (background dark)) (:foreground "light coral")) 
			      (((class color) (background light)) (:foreground "green4")) (t (:bold t))))
 '(font-lock-preprocessor-face ((((type tty) (class color)) (:foreground "brightblue")) 
				(((class color) (background dark)) (:foreground "steelblue1")) 
				(((class color) (background light)) (:foreground "blue3")) (t (:underline t))))
 '(font-lock-variable-name-face ((((type tty) (class color)) (:foreground "brightcyan")) 
				 (((class color) (background dark)) (:foreground "cyan3")) 
				 (((class color) (background light)) (:foreground "magenta4")) 
				 (((class grayscale) (background light)) (:foreground "Gray90" :bold t :italic t)) 
				 (((class grayscale) (background dark)) (:foreground "DimGray" :bold t :italic t)) (t (:underline t))))
 '(paren-match ((((type x) (class color)) (:background "seagreen1")) 
		(((type tty) (class color)) (:foreground "white" :background "green"))) t)
 '(font-lock-warning-face ((((type tty) (class color)) (:foreground "brightred")) 
			   (((class color) (background light)) (:foreground "Red" :bold t)) 
			   (((class color) (background dark)) (:foreground "Pink" :bold t)) (t (:bold t :inverse-video t))))
 '(font-lock-keyword-face ((((type tty) (class color)) (:foreground "brightwhite")) 
			   (((class color) (background light)) (:foreground "red4" :bold t))))
 '(font-lock-type-face ((((type tty) (class color)) (:foreground "brightmagenta")) 
			(((class color) (background dark)) (:foreground "wheat")) 
			(((class color) (background light)) (:foreground "steelblue")) 
			(((class grayscale) (background light)) (:foreground "Gray90" :bold t)) 
			(((class grayscale) (background dark)) (:foreground "DimGray" :bold t)) (t (:bold t))))
 '(font-lock-other-type-face ((((type x) (class color)) (:foreground "blue3")) (t (:foreground "brightblue"))) t)
 '(font-lock-comment-face ((((type tty) (class color)) (:foreground "yellow")) 
			   (((class color) (background dark)) (:foreground "gray80")) 
			   (((class color) (background light)) (:foreground "blue4")) 
			   (((class grayscale) (background light)) (:foreground "DimGray" :bold t :italic t)) 
			   (((class grayscale) (background dark)) (:foreground "LightGray" :bold t :italic t)) (t (:bold t))))
 '(dired-face-executable ((((type x) (class color) (background light)) (:foreground "green4" :bold t)) 
			  (((type tty) (class color) (background dark)) (:foreground "green" :bold t))))
 '(font-lock-function-name-face ((((type tty) (class color)) (:foreground "blue")) 
				 (((class color) (background dark)) (:foreground "aquamarine")) 
				 (((class color) (background light)) (:foreground "brown4")) (t (:bold t :underline t))))
 '(modeline ((((type x) (class color) (background light)) (:background "grey80")) 
	     (((type tty) (class color)) (:foreground "black" :background "cyan"))) t)
 '(dired-face-symlink ((((type x) (class color)) (:foreground "cyan4")) 
		       (((type tty) (class color)) (:foreground "cyan")) (t (:bold t))))
 '(mutt-header-keyword-face ((((type tty) (class color)) (:foreground "brightgreen")) 
			     (((class color) (background dark)) (:foreground "light coral")) 
			     (((class color) (background light)) (:foreground "green4")) (t (:bold t))))
 '(mutt-quoted-text-face ((((type tty) (class color)) (:foreground "yellow")) 
			  (((class color) (background dark)) (:foreground "gray80")) 
			  (((class color) (background light)) (:foreground "blue4")) 
			  (((class grayscale) (background light)) (:foreground "DimGray" :bold t :italic t)) 
			  (((class grayscale) (background dark)) (:foreground "LightGray" :bold t :italic t)) (t (:bold t))))
 '(yellow ((((type x) (class color) (background light)) (:foreground "yellow4")) 
	   (((type tty) (class color)) (:foreground "brightyellow"))) t)
 '(green ((((type x) (class color)) (:foreground "green4")) (t (:foreground "green"))) t)
 )